build_root:
  project_image:
    dockerfile_path: Dockerfile.prow
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: capz-e2e
  commands: |
    source openshift-ci/capz-test-env.sh
    export TEST_RESULTS_DIR="${ARTIFACT_DIR}"
    gotestsum --junitfile="${ARTIFACT_DIR}/junit-e2e.xml" -- \
      -v ./test -count=1 -timeout 30m \
      -run "TestCheckDependencies|TestSetup|TestManagementCluster|TestInfrastructure"
  container:
    from: src
  timeout: 30m0s
zz_generated_metadata:
  branch: configure-prow
  org: stolostron
  repo: capi-tests
