build_root:
  image_stream_tag:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.24-openshift-4.20
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: check-dependencies
  steps:
    test:
    - ref: capz-test-check-dependencies
- as: capz-e2e
  cluster_profile: azure4
  steps:
    pre:
    - ref: ipi-conf
    - ref: ipi-conf-azure
    - ref: ipi-install
    - ref: capz-test-install-controllers
    test:
    - ref: capz-test-e2e
    post:
    - ref: ipi-deprovision-deprovision
  timeout: 4h0m0s
zz_generated_metadata:
  branch: main
  org: stolostron
  repo: capi-tests
